server:
  port: 8091
  
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/users-database
    url: jdbc:mysql://mysql_database:3306/users-database
    username: tfg
    password: tfg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
jwt:
  secret: secret
  expiration: 3600