server:
  port: 8092
  
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/bookings-database
    url: jdbc:mysql://mysql_database:3306/bookings-database
    username: tfg
    password: tfg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true