version: "3.1"
services:
  users-service:
    image: rubencg177/notification-service:latest
    container_name: users
    ports:
      - 8093:8093
    networks:
      - mysql_default
networks:
  mysql_default:
    external: true