version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk11
    container_name: jenkins
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - /media/ruben/ext4-drive/docker/jenkins_home:/var/jenkins_home
    user: root
  agent:
    image: rubencg177/ssh-agent-with-docker:alpine-jdk8
    container_name: agent
    privileged: true
    expose:
      - 22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_KEY}